apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ciscoaciaim-operator-role
  namespace: openstack-operators
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ciscoaciaim-operator-rolebinding
  namespace: openstack-operators
subjects:
- kind: ServiceAccount
  name: default
  namespace: openstack-operators
roleRef:
  kind: Role
  name: ciscoaciaim-operator-role
  apiGroup: rbac.authorization.k8s.io
