apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ciscoaciaim-operator-role
rules:
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims
  - ciscoaciaims/status
  - ciscoaciaims/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ciscoaciaim-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: openstack-operators
roleRef:
  kind: ClusterRole
  name: ciscoaciaim-operator-role
  apiGroup: rbac.authorization.k8s.io
