apiVersion: v1
kind: Namespace
metadata:
  name: openstack-aim
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ciscoaci-aim
  namespace: openstack-aim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ciscoaci-aim-role
  namespace: openstack-aim
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # Add more rules as needed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ciscoaci-aim-rolebinding
  namespace: openstack-aim
subjects:
  - kind: ServiceAccount
    name: ciscoaci-aim
    namespace: openstack-aim
roleRef:
  kind: Role
  name: ciscoaci-aim-role
  apiGroup: rbac.authorization.k8s.io
