---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims/finalizers
  - ciscoaciaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbaccounts
  - mariadbdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronapis/status
  verbs:
  - get
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
