---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims/finalizers
  verbs:
  - update
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - galeras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - rabbitmqclusters
  verbs:
  - get
  - list
  - watch
